### ISSUE TITLE
API 요청: 현재 카드 만들 수 있는 상황인지??

### ISSUE THREAD

**Issue by krgoodnews** [potenday16/backend#11]

**Comment by 0703kyj** [comment]
http://49.50.160.149:8080/swagger-ui/index.html#/
이 곳에서 확인 가능합니다!

https://www.notion.so/API-6739034700144ab2803b90af59c358dc?pvs=4
추가적으로 스펙중에 헷갈릴만한 부분을 노션에 일부 적어 놨으니 확인 부탁드려요 😄

**Comment by rolroralra** [comment]
> http://49.50.160.149:8080/swagger-ui/index.html#/ 이 곳에서 확인 가능합니다!
> 
> https://www.notion.so/API-6739034700144ab2803b90af59c358dc?pvs=4 추가적으로 스펙중에 헷갈릴만한 부분을 노션에 일부 적어 놨으니 확인 부탁드려요 😄

👍
